### PR TITLE
makes "Register Navigation" property configurable

### PR DESCRIPTION
**Pull request by alvleont**
It adds the line into config and the function into Activity Resource to make the plugin "hideable"

### CODE REVIEW

**Comment by alvleont** [comment]
Is it the same? I mean. I was thinking on having the chance to get this option a more customizable way, not being just another button inside menu (maybe inside a more complex admin page...)

**Comment by Z3d0X** [comment]
`shouldRegisterNavigation` just hides the Resource from navigation, meaning it's still accessible, if you go to that route..

Doing it through policy handles both hiding the navigation item, and also does a authorization check.

**Comment by alvleont** [comment]
Exactly. What if i wanted to just hide from navigation and put it into User Menu? (It's not only my case. Some of discord's comments are trough that line of customization.

**Comment by Z3d0X** [comment]
In that case, you can provide provide your own resource for Activity.
https://github.com/Z3d0X/filament-logger/blob/main/config/filament-logger.php#L6

I can't go adding every single feature Filament `Resource` offers to the config

**Pull request closed without merging**
